name: Auto Generate Comic Scripts

on:
  schedule:
    # 每小時執行一次 (UTC 時間)
    - cron: '0 * * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  generate-comics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 需要 token 來推送更改
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run comic generation
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        python main.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add outputs/
        
        # 檢查是否有變更需要提交
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generated comic scripts - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
